// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: can_gateway.proto

#ifndef PROTOBUF_INCLUDED_can_5fgateway_2eproto
#define PROTOBUF_INCLUDED_can_5fgateway_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_can_5fgateway_2eproto 

namespace protobuf_can_5fgateway_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_can_5fgateway_2eproto
namespace can_gateway {
class CANMsgData;
class CANMsgDataDefaultTypeInternal;
extern CANMsgDataDefaultTypeInternal _CANMsgData_default_instance_;
class CANMsgDataList;
class CANMsgDataListDefaultTypeInternal;
extern CANMsgDataListDefaultTypeInternal _CANMsgDataList_default_instance_;
}  // namespace can_gateway
namespace google {
namespace protobuf {
template<> ::can_gateway::CANMsgData* Arena::CreateMaybeMessage<::can_gateway::CANMsgData>(Arena*);
template<> ::can_gateway::CANMsgDataList* Arena::CreateMaybeMessage<::can_gateway::CANMsgDataList>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace can_gateway {

// ===================================================================

class CANMsgData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:can_gateway.CANMsgData) */ {
 public:
  CANMsgData();
  virtual ~CANMsgData();

  CANMsgData(const CANMsgData& from);

  inline CANMsgData& operator=(const CANMsgData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CANMsgData(CANMsgData&& from) noexcept
    : CANMsgData() {
    *this = ::std::move(from);
  }

  inline CANMsgData& operator=(CANMsgData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CANMsgData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CANMsgData* internal_default_instance() {
    return reinterpret_cast<const CANMsgData*>(
               &_CANMsgData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(CANMsgData* other);
  friend void swap(CANMsgData& a, CANMsgData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CANMsgData* New() const final {
    return CreateMaybeMessage<CANMsgData>(NULL);
  }

  CANMsgData* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CANMsgData>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CANMsgData& from);
  void MergeFrom(const CANMsgData& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CANMsgData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes Bytes = 7;
  void clear_bytes();
  static const int kBytesFieldNumber = 7;
  const ::std::string& bytes() const;
  void set_bytes(const ::std::string& value);
  #if LANG_CXX11
  void set_bytes(::std::string&& value);
  #endif
  void set_bytes(const char* value);
  void set_bytes(const void* value, size_t size);
  ::std::string* mutable_bytes();
  ::std::string* release_bytes();
  void set_allocated_bytes(::std::string* bytes);

  // uint32 CANChannel = 1;
  void clear_canchannel();
  static const int kCANChannelFieldNumber = 1;
  ::google::protobuf::uint32 canchannel() const;
  void set_canchannel(::google::protobuf::uint32 value);

  // uint32 CanId = 2;
  void clear_canid();
  static const int kCanIdFieldNumber = 2;
  ::google::protobuf::uint32 canid() const;
  void set_canid(::google::protobuf::uint32 value);

  // bool f_RTR = 3;
  void clear_f_rtr();
  static const int kFRTRFieldNumber = 3;
  bool f_rtr() const;
  void set_f_rtr(bool value);

  // bool f_CANFD = 4;
  void clear_f_canfd();
  static const int kFCANFDFieldNumber = 4;
  bool f_canfd() const;
  void set_f_canfd(bool value);

  // bool f_IDE = 5;
  void clear_f_ide();
  static const int kFIDEFieldNumber = 5;
  bool f_ide() const;
  void set_f_ide(bool value);

  // uint32 CanDataLen = 6;
  void clear_candatalen();
  static const int kCanDataLenFieldNumber = 6;
  ::google::protobuf::uint32 candatalen() const;
  void set_candatalen(::google::protobuf::uint32 value);

  // uint32 seconds = 8;
  void clear_seconds();
  static const int kSecondsFieldNumber = 8;
  ::google::protobuf::uint32 seconds() const;
  void set_seconds(::google::protobuf::uint32 value);

  // uint32 nanoseconds = 9;
  void clear_nanoseconds();
  static const int kNanosecondsFieldNumber = 9;
  ::google::protobuf::uint32 nanoseconds() const;
  void set_nanoseconds(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:can_gateway.CANMsgData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr bytes_;
  ::google::protobuf::uint32 canchannel_;
  ::google::protobuf::uint32 canid_;
  bool f_rtr_;
  bool f_canfd_;
  bool f_ide_;
  ::google::protobuf::uint32 candatalen_;
  ::google::protobuf::uint32 seconds_;
  ::google::protobuf::uint32 nanoseconds_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_can_5fgateway_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CANMsgDataList : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:can_gateway.CANMsgDataList) */ {
 public:
  CANMsgDataList();
  virtual ~CANMsgDataList();

  CANMsgDataList(const CANMsgDataList& from);

  inline CANMsgDataList& operator=(const CANMsgDataList& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CANMsgDataList(CANMsgDataList&& from) noexcept
    : CANMsgDataList() {
    *this = ::std::move(from);
  }

  inline CANMsgDataList& operator=(CANMsgDataList&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CANMsgDataList& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CANMsgDataList* internal_default_instance() {
    return reinterpret_cast<const CANMsgDataList*>(
               &_CANMsgDataList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(CANMsgDataList* other);
  friend void swap(CANMsgDataList& a, CANMsgDataList& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CANMsgDataList* New() const final {
    return CreateMaybeMessage<CANMsgDataList>(NULL);
  }

  CANMsgDataList* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CANMsgDataList>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CANMsgDataList& from);
  void MergeFrom(const CANMsgDataList& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CANMsgDataList* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .can_gateway.CANMsgData messages = 1;
  int messages_size() const;
  void clear_messages();
  static const int kMessagesFieldNumber = 1;
  ::can_gateway::CANMsgData* mutable_messages(int index);
  ::google::protobuf::RepeatedPtrField< ::can_gateway::CANMsgData >*
      mutable_messages();
  const ::can_gateway::CANMsgData& messages(int index) const;
  ::can_gateway::CANMsgData* add_messages();
  const ::google::protobuf::RepeatedPtrField< ::can_gateway::CANMsgData >&
      messages() const;

  // @@protoc_insertion_point(class_scope:can_gateway.CANMsgDataList)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::can_gateway::CANMsgData > messages_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_can_5fgateway_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CANMsgData

// uint32 CANChannel = 1;
inline void CANMsgData::clear_canchannel() {
  canchannel_ = 0u;
}
inline ::google::protobuf::uint32 CANMsgData::canchannel() const {
  // @@protoc_insertion_point(field_get:can_gateway.CANMsgData.CANChannel)
  return canchannel_;
}
inline void CANMsgData::set_canchannel(::google::protobuf::uint32 value) {
  
  canchannel_ = value;
  // @@protoc_insertion_point(field_set:can_gateway.CANMsgData.CANChannel)
}

// uint32 CanId = 2;
inline void CANMsgData::clear_canid() {
  canid_ = 0u;
}
inline ::google::protobuf::uint32 CANMsgData::canid() const {
  // @@protoc_insertion_point(field_get:can_gateway.CANMsgData.CanId)
  return canid_;
}
inline void CANMsgData::set_canid(::google::protobuf::uint32 value) {
  
  canid_ = value;
  // @@protoc_insertion_point(field_set:can_gateway.CANMsgData.CanId)
}

// bool f_RTR = 3;
inline void CANMsgData::clear_f_rtr() {
  f_rtr_ = false;
}
inline bool CANMsgData::f_rtr() const {
  // @@protoc_insertion_point(field_get:can_gateway.CANMsgData.f_RTR)
  return f_rtr_;
}
inline void CANMsgData::set_f_rtr(bool value) {
  
  f_rtr_ = value;
  // @@protoc_insertion_point(field_set:can_gateway.CANMsgData.f_RTR)
}

// bool f_CANFD = 4;
inline void CANMsgData::clear_f_canfd() {
  f_canfd_ = false;
}
inline bool CANMsgData::f_canfd() const {
  // @@protoc_insertion_point(field_get:can_gateway.CANMsgData.f_CANFD)
  return f_canfd_;
}
inline void CANMsgData::set_f_canfd(bool value) {
  
  f_canfd_ = value;
  // @@protoc_insertion_point(field_set:can_gateway.CANMsgData.f_CANFD)
}

// bool f_IDE = 5;
inline void CANMsgData::clear_f_ide() {
  f_ide_ = false;
}
inline bool CANMsgData::f_ide() const {
  // @@protoc_insertion_point(field_get:can_gateway.CANMsgData.f_IDE)
  return f_ide_;
}
inline void CANMsgData::set_f_ide(bool value) {
  
  f_ide_ = value;
  // @@protoc_insertion_point(field_set:can_gateway.CANMsgData.f_IDE)
}

// uint32 CanDataLen = 6;
inline void CANMsgData::clear_candatalen() {
  candatalen_ = 0u;
}
inline ::google::protobuf::uint32 CANMsgData::candatalen() const {
  // @@protoc_insertion_point(field_get:can_gateway.CANMsgData.CanDataLen)
  return candatalen_;
}
inline void CANMsgData::set_candatalen(::google::protobuf::uint32 value) {
  
  candatalen_ = value;
  // @@protoc_insertion_point(field_set:can_gateway.CANMsgData.CanDataLen)
}

// bytes Bytes = 7;
inline void CANMsgData::clear_bytes() {
  bytes_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CANMsgData::bytes() const {
  // @@protoc_insertion_point(field_get:can_gateway.CANMsgData.Bytes)
  return bytes_.GetNoArena();
}
inline void CANMsgData::set_bytes(const ::std::string& value) {
  
  bytes_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:can_gateway.CANMsgData.Bytes)
}
#if LANG_CXX11
inline void CANMsgData::set_bytes(::std::string&& value) {
  
  bytes_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:can_gateway.CANMsgData.Bytes)
}
#endif
inline void CANMsgData::set_bytes(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  bytes_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:can_gateway.CANMsgData.Bytes)
}
inline void CANMsgData::set_bytes(const void* value, size_t size) {
  
  bytes_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:can_gateway.CANMsgData.Bytes)
}
inline ::std::string* CANMsgData::mutable_bytes() {
  
  // @@protoc_insertion_point(field_mutable:can_gateway.CANMsgData.Bytes)
  return bytes_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CANMsgData::release_bytes() {
  // @@protoc_insertion_point(field_release:can_gateway.CANMsgData.Bytes)
  
  return bytes_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CANMsgData::set_allocated_bytes(::std::string* bytes) {
  if (bytes != NULL) {
    
  } else {
    
  }
  bytes_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), bytes);
  // @@protoc_insertion_point(field_set_allocated:can_gateway.CANMsgData.Bytes)
}

// uint32 seconds = 8;
inline void CANMsgData::clear_seconds() {
  seconds_ = 0u;
}
inline ::google::protobuf::uint32 CANMsgData::seconds() const {
  // @@protoc_insertion_point(field_get:can_gateway.CANMsgData.seconds)
  return seconds_;
}
inline void CANMsgData::set_seconds(::google::protobuf::uint32 value) {
  
  seconds_ = value;
  // @@protoc_insertion_point(field_set:can_gateway.CANMsgData.seconds)
}

// uint32 nanoseconds = 9;
inline void CANMsgData::clear_nanoseconds() {
  nanoseconds_ = 0u;
}
inline ::google::protobuf::uint32 CANMsgData::nanoseconds() const {
  // @@protoc_insertion_point(field_get:can_gateway.CANMsgData.nanoseconds)
  return nanoseconds_;
}
inline void CANMsgData::set_nanoseconds(::google::protobuf::uint32 value) {
  
  nanoseconds_ = value;
  // @@protoc_insertion_point(field_set:can_gateway.CANMsgData.nanoseconds)
}

// -------------------------------------------------------------------

// CANMsgDataList

// repeated .can_gateway.CANMsgData messages = 1;
inline int CANMsgDataList::messages_size() const {
  return messages_.size();
}
inline void CANMsgDataList::clear_messages() {
  messages_.Clear();
}
inline ::can_gateway::CANMsgData* CANMsgDataList::mutable_messages(int index) {
  // @@protoc_insertion_point(field_mutable:can_gateway.CANMsgDataList.messages)
  return messages_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::can_gateway::CANMsgData >*
CANMsgDataList::mutable_messages() {
  // @@protoc_insertion_point(field_mutable_list:can_gateway.CANMsgDataList.messages)
  return &messages_;
}
inline const ::can_gateway::CANMsgData& CANMsgDataList::messages(int index) const {
  // @@protoc_insertion_point(field_get:can_gateway.CANMsgDataList.messages)
  return messages_.Get(index);
}
inline ::can_gateway::CANMsgData* CANMsgDataList::add_messages() {
  // @@protoc_insertion_point(field_add:can_gateway.CANMsgDataList.messages)
  return messages_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::can_gateway::CANMsgData >&
CANMsgDataList::messages() const {
  // @@protoc_insertion_point(field_list:can_gateway.CANMsgDataList.messages)
  return messages_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace can_gateway

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_can_5fgateway_2eproto
