/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.13 Fri Jan 16 10:59:19 2026.
 */

#ifndef VEH_DBC_H
#define VEH_DBC_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define VEH_DBC_AD_CONTROL_DEVICE_FRAME_ID (0x508u)
#define VEH_DBC_AD_SETUP_CONTROL_FRAME_ID (0x507u)
#define VEH_DBC_SYSTEM_POWER_CONTROL_FRAME_ID (0x50bu)
#define VEH_DBC_POWER_ON_CAN_FRAME_ID (0x50au)
#define VEH_DBC_AD_CONTROL_BODY_FRAME_ID (0x506u)
#define VEH_DBC_AD_CONTROL_ACCELERATE_FRAME_ID (0x504u)
#define VEH_DBC_AD_CONTROL_BRAKE_FRAME_ID (0x503u)
#define VEH_DBC_AD_CONTROL_STEERING_FRAME_ID (0x502u)

/* Frame lengths in bytes. */
#define VEH_DBC_AD_CONTROL_DEVICE_LENGTH (8u)
#define VEH_DBC_AD_SETUP_CONTROL_LENGTH (8u)
#define VEH_DBC_SYSTEM_POWER_CONTROL_LENGTH (8u)
#define VEH_DBC_POWER_ON_CAN_LENGTH (8u)
#define VEH_DBC_AD_CONTROL_BODY_LENGTH (8u)
#define VEH_DBC_AD_CONTROL_ACCELERATE_LENGTH (8u)
#define VEH_DBC_AD_CONTROL_BRAKE_LENGTH (8u)
#define VEH_DBC_AD_CONTROL_STEERING_LENGTH (8u)

/* Extended or standard frame types. */
#define VEH_DBC_AD_CONTROL_DEVICE_IS_EXTENDED (0)
#define VEH_DBC_AD_SETUP_CONTROL_IS_EXTENDED (0)
#define VEH_DBC_SYSTEM_POWER_CONTROL_IS_EXTENDED (0)
#define VEH_DBC_POWER_ON_CAN_IS_EXTENDED (0)
#define VEH_DBC_AD_CONTROL_BODY_IS_EXTENDED (0)
#define VEH_DBC_AD_CONTROL_ACCELERATE_IS_EXTENDED (0)
#define VEH_DBC_AD_CONTROL_BRAKE_IS_EXTENDED (0)
#define VEH_DBC_AD_CONTROL_STEERING_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */
#define VEH_DBC_AD_SETUP_CONTROL_CYCLE_TIME_MS (20u)
#define VEH_DBC_SYSTEM_POWER_CONTROL_CYCLE_TIME_MS (20u)
#define VEH_DBC_POWER_ON_CAN_CYCLE_TIME_MS (20u)
#define VEH_DBC_AD_CONTROL_BODY_CYCLE_TIME_MS (20u)
#define VEH_DBC_AD_CONTROL_ACCELERATE_CYCLE_TIME_MS (20u)
#define VEH_DBC_AD_CONTROL_BRAKE_CYCLE_TIME_MS (20u)
#define VEH_DBC_AD_CONTROL_STEERING_CYCLE_TIME_MS (20u)

/* Signal choices. */


/* Frame Names. */
#define VEH_DBC_AD_CONTROL_DEVICE_NAME "AD_Control_Device"
#define VEH_DBC_AD_SETUP_CONTROL_NAME "AD_Setup_Control"
#define VEH_DBC_SYSTEM_POWER_CONTROL_NAME "System_Power_Control"
#define VEH_DBC_POWER_ON_CAN_NAME "Power_on_CAN"
#define VEH_DBC_AD_CONTROL_BODY_NAME "AD_Control_Body"
#define VEH_DBC_AD_CONTROL_ACCELERATE_NAME "AD_Control_Accelerate"
#define VEH_DBC_AD_CONTROL_BRAKE_NAME "AD_Control_Brake"
#define VEH_DBC_AD_CONTROL_STEERING_NAME "AD_Control_Steering"

/* Signal Names. */
#define VEH_DBC_AD_CONTROL_DEVICE_AD_CLEAN_FAN_NAME "AD_Clean_Fan"
#define VEH_DBC_AD_CONTROL_DEVICE_AD_MOVE_MODE_REQ_NAME "AD_MoveMode_Req"
#define VEH_DBC_AD_SETUP_CONTROL_AD_RELEASE_EMERGENCY_BUTTON_NAME "AD_Release_Emergency_Button"
#define VEH_DBC_AD_SETUP_CONTROL_AD_RELEASE_F_BUMPER_NAME "AD_Release_F_Bumper"
#define VEH_DBC_AD_SETUP_CONTROL_AD_RELEASE_B_BUMPER_NAME "AD_Release_B_Bumper"
#define VEH_DBC_AD_SETUP_CONTROL_AD_RELEASE_L_BUMPER_NAME "AD_Release_L_Bumper"
#define VEH_DBC_AD_SETUP_CONTROL_AD_RELEASE_R_BUMPER_NAME "AD_Release_R_Bumper"
#define VEH_DBC_AD_SETUP_CONTROL_AD_CLEAR_TRIP_NAME "AD_Clear_TRIP"
#define VEH_DBC_AD_SETUP_CONTROL_AD_DISABLE_F_BUMPER_NAME "AD_Disable_F_Bumper"
#define VEH_DBC_AD_SETUP_CONTROL_AD_DISABLE_B_BUMPER_NAME "AD_Disable_B_Bumper"
#define VEH_DBC_AD_SETUP_CONTROL_AD_DISABLE_L_BUMPER_NAME "AD_Disable_L_Bumper"
#define VEH_DBC_AD_SETUP_CONTROL_AD_DISABLE_R_BUMPER_NAME "AD_Disable_R_Bumper"
#define VEH_DBC_AD_SETUP_CONTROL_CAN_SIGN_TRAN_STATE_NAME "CAN_Sign_tran_State"
#define VEH_DBC_AD_SETUP_CONTROL_AD_VEHICLE_WEIGHT_NAME "AD_VehicleWeight"
#define VEH_DBC_SYSTEM_POWER_CONTROL_AD_SYS_POWER_CONTROL_NAME "AD_Sys_Power_Control"
#define VEH_DBC_SYSTEM_POWER_CONTROL_RESERVED_SYS_POWER_CONTROL_NAME "Reserved_Sys_Power_Control"
#define VEH_DBC_SYSTEM_POWER_CONTROL_NETWORK_SYS_POWER_CONTROL_NAME "Network_Sys_Power_Control"
#define VEH_DBC_SYSTEM_POWER_CONTROL_RADAR_SYS_POWER_CONTROL_NAME "Radar_Sys_Power_Control"
#define VEH_DBC_SYSTEM_POWER_CONTROL_BUSINESS_SYS_POWER_CONTROL_NAME "Business_Sys_Power_Control"
#define VEH_DBC_SYSTEM_POWER_CONTROL_VEHICLE_WORK_MODE_CONTROL_NAME "Vehicle_Work_Mode_Control"
#define VEH_DBC_POWER_ON_CAN_VEHICLE_POWER_REQ_NAME "Vehicle_Power_Req"
#define VEH_DBC_POWER_ON_CAN_AD_POWER_OFF_DELAY_TIME_NAME "AD_PowerOff_DelayTime"
#define VEH_DBC_AD_CONTROL_BODY_AD_BODY_VALID_NAME "AD_Body_Valid"
#define VEH_DBC_AD_CONTROL_BODY_AD_BRAKE_LIGHT_NAME "AD_Brake_Light"
#define VEH_DBC_AD_CONTROL_BODY_AD_DOUBLE_FLASH_LIGHT_NAME "AD_Double_Flash_Light"
#define VEH_DBC_AD_CONTROL_BODY_AD_REVERSING_LIGHTS_NAME "AD_Reversing_Lights"
#define VEH_DBC_AD_CONTROL_BODY_AD_LOW_BEAM_NAME "AD_Low_Beam"
#define VEH_DBC_AD_CONTROL_BODY_AD_LEFT_TURN_LIGHT_NAME "AD_Left_Turn_Light"
#define VEH_DBC_AD_CONTROL_BODY_AD_RIGHT_TURN_LIGHT_NAME "AD_Right_Turn_Light"
#define VEH_DBC_AD_CONTROL_BODY_AD_HORN_CONTROL_NAME "AD_Horn_Control"
#define VEH_DBC_AD_CONTROL_BODY_AD_HIGH_BEAM_NAME "AD_High_Beam"
#define VEH_DBC_AD_CONTROL_BODY_AD_FOF_LIGHT_NAME "AD_Fof_Light"
#define VEH_DBC_AD_CONTROL_BODY_AD_HORN_CONTROL_1_NAME "AD_Horn_Control_1"
#define VEH_DBC_AD_CONTROL_ACCELERATE_AD_ACCELERATE_VALID_NAME "AD_Accelerate_Valid"
#define VEH_DBC_AD_CONTROL_ACCELERATE_AD_ENERGY_RECOVERY_NAME "AD_Energy_Recovery"
#define VEH_DBC_AD_CONTROL_ACCELERATE_AD_ACCELERATE_WORK_MODE_NAME "AD_Accelerate_Work_Mode"
#define VEH_DBC_AD_CONTROL_ACCELERATE_AD_ACCELERATE_GEAR_NAME "AD_Accelerate_Gear"
#define VEH_DBC_AD_CONTROL_ACCELERATE_AD_TORQUE_CONTROL_NAME "AD_Torque_Control"
#define VEH_DBC_AD_CONTROL_ACCELERATE_AD_SPEEDOR_TORQUE_CONTROL_NAME "AD_SpeedorTorque_Control"
#define VEH_DBC_AD_CONTROL_BRAKE_AD_DBS_VALID_NAME "AD_DBS_Valid"
#define VEH_DBC_AD_CONTROL_BRAKE_AD_AWSC_FLAG_NAME "AD_AWSC_Flag"
#define VEH_DBC_AD_CONTROL_BRAKE_AD_DBS_WORKMODE_NAME "AD_DBS_Workmode"
#define VEH_DBC_AD_CONTROL_BRAKE_AD_BRAKE_PRESSURE_CMD_NAME "AD_BrakePressure_Cmd"
#define VEH_DBC_AD_CONTROL_STEERING_AD_STEERING_VALID_NAME "AD_Steering_Valid"
#define VEH_DBC_AD_CONTROL_STEERING_AD_STEERING_SPEED_CMD_NAME "AD_Steering_Speed_Cmd"
#define VEH_DBC_AD_CONTROL_STEERING_AD_STEERING_ANGLE_CMD_NAME "AD_Steering_Angle_Cmd"

/**
 * Signals in message AD_Control_Device.
 *
 * All signal values are as on the CAN bus.
 */
struct veh_dbc_ad_control_device_t {
    /**
     * Çå½à·ç»ú¿ª¹Ø£º
     * 0£º²»¿ªÆô
     * 1£º¿ªÆô
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_clean_fan;

    /**
     * ×Ô¶¯¼ÝÊ»¿ØÖÆ³µÁ¾Å²³µÄ£Ê½
     *
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_move_mode_req;
};

/**
 * Signals in message AD_Setup_Control.
 *
 * ½â³ý¼±Í£ºÍBumper£¬Çå³ýÐ¡Àï³Ì¡£
´ËÏûÏ¢²»·¢£¬È«¶¼Ä¬ÈÏÎ´0
 *
 * All signal values are as on the CAN bus.
 */
struct veh_dbc_ad_setup_control_t {
    /**
     * 0ÎÞÐ§£¬1½â³ý¼±Í£°´Å¥
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_release_emergency_button;

    /**
     * 0ÎÞÐ§£¬1½â³ýÇ°Bumper
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_release_f_bumper;

    /**
     * 0ÎÞÐ§£¬1½â³ýºóBumper
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_release_b_bumper;

    /**
     * 0ÎÞÐ§£¬1½â³ý×óBumper
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_release_l_bumper;

    /**
     * 0ÎÞÐ§£¬1½â³ýÓÒBumper
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_release_r_bumper;

    /**
     * 0ÎÞÐ§£¬1Çå³ýÐ¡Àï³Ì
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_clear_trip;

    /**
     * 0 ½â³ý½ûÓÃÇ°Bumper
     * 1 ½ûÓÃÇ°Bumper
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_disable_f_bumper;

    /**
     * 0 ½â³ý½ûÓÃºóBumper
     * 1 ½ûÓÃºóBumper
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_disable_b_bumper;

    /**
     * 0 ½â³ý½ûÓÃ×óBumper
     * 1 ½ûÓÃ×óBumper
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_disable_l_bumper;

    /**
     * 0 ½â³ý½ûÓÃÓÒBumper
     * 1 ½ûÓÃÓÒBumper
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_disable_r_bumper;

    /**
     * ×ª·¢ÐÅºÅ¿ªÆô±êÖ¾
     * 0£º×ª·¢
     * 1£º²»×ª·¢
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t can_sign_tran_state;

    /**
     * Õû³µÖØÁ¿
     *
     * Range: 0..8191 (0..8191 kg)
     * Scale: 1
     * Offset: 0
     */
    uint16_t ad_vehicle_weight;
};

/**
 * Signals in message System_Power_Control.
 *
 * 5¸ö×ÓÏµÍ³£¬·Ö±ðÎª×Ô¶¯¼ÝÊ»ÏµÍ³¡¢²¹Ã¤À×´ïÏµÍ³£¬ÒµÎñÏµÍ³¡¢¼à¿ØÏµÍ³¡¢4GÍøÂçÏµÍ³
ÉÏÏÂµç¿ØÖÆ
 *
 * All signal values are as on the CAN bus.
 */
struct veh_dbc_system_power_control_t {
    /**
     * ×Ô¶¯¼ÝÊ»ÏµÍ³ÉÏÏÂµç¿ØÖÆ Ä¬ÈÏÉÏµç
     * 0ÏÂµç£¬1ÉÏµç£¬2±£³Ö
     *
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_sys_power_control;

    /**
     * Ô¤ÁôÏµÍ³ÉÏÏÂµç¿ØÖÆ  Ä¬ÈÏÉÏµç
     * 0ÏÂµç£¬1ÉÏµç£¬2±£³Ö
     * ZL00042¡¢ZL00043³µÐÍ¸Ã½Ó¿ÚÅäÖÃÊÇMonitorÏµÍ³µÄÉÏÏÂµç¿ØÖÆ½Ó¿Ú£¬Òò´ËÎªÁËÈí¼þÄÜ¼æÈÝÇ°Á½Ì¨³µÐÍ£¬¸Ã×Ö¶ÎÐèÒªÄ¬ÈÏ·¢1£¬ÕâÑùÇ°Á½Ì¨³µÐÍµÄMonitor²ÅÄÜ³¤ÆÚ±£³ÖÉÏµç
     *
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t reserved_sys_power_control;

    /**
     * 4GÍøÂçÏµÍ³ÉÏÏÂµç¿ØÖÆ  Ä¬ÈÏÉÏµç
     * 0ÏÂµç£¬1ÉÏµç£¬2±£³Ö£¬3ÖØÆô
     *
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t network_sys_power_control;

    /**
     * ²¹Ã¤À×´ïÏµÍ³ÉÏÏÂµç¿ØÖÆ Ä¬ÈÏÉÏµç
     * 0ÏÂµç£¬1ÉÏµç£¬2±£³Ö£¬3ÖØÆô
     *
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t radar_sys_power_control;

    /**
     * ÒµÎñÏµÍ³ÉÏÏÂµç¿ØÖÆ Ä¬ÈÏÉÏµç
     * 0ÏÂµç£¬1ÉÏµç£¬2±£³Ö£¬3ÖØÆô
     *
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t business_sys_power_control;

    /**
     * Ä¬ÈÏ²»·¢ÎªÕý³£¹¤×÷Ä£Ê½
     * 0ÎªÕý³£¹¤×÷Ä£Ê½
     * 1ÎªÁÙÊ±Í£³µ
     * 2Îª³¤Ê±¼äÍ£³µ
     *
     * Range: 0..3 (0..3 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t vehicle_work_mode_control;
};

/**
 * Signals in message Power_on_CAN.
 *
 * Ô¶³ÌÉÏµçÐÅºÅ

 *
 * All signal values are as on the CAN bus.
 */
struct veh_dbc_power_on_can_t {
    /**
     * µ×ÅÌ×ÜµçÔ´
     * 0¹Ø»ú£¨µ×ÅÌ¡¢»õÏäÏµÍ³¾ù¶Ïµç£©
     * 1¿ª»ú£¨µ×ÅÌ¡¢»õÏäÏµÍ³¾ùÉÏµç£©
     * 2±£³Öµ×ÅÌµ±Ç°×´Ì¬
     * 3ÖØÆô£¨µ×ÅÌ¹Ø»ú2sºó£¬ÔÙ¿ª»ú¡£Ö»ÄÜÔÚµ×ÅÌÉÏµçµÄÇé¿öÏÂ·¢ÖØÆô²Å»áÉúÐ§£©
     * 4Á¢¼´ÏÂµç£¨Ö»ÏàÓ¦5µ¹¼ÆÊ±£¬ÊÕµ½¸ÃÖ¸Áî×´Ì¬£¬Á¢¼´ÏÂµç£¬Ö±½Ó·¢¸ÃÖ¸Áî²»ÏìÓ¦£©
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t vehicle_power_req;

    /**
     * ×Ô¼ÝÏÂµçÑÓÊ±Ê±¼ä
     * 
     * 0£ºÄ¬ÈÏÊ±¼ä£¨30S£©
     *
     * Range: 0..63 (0..63 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_power_off_delay_time;
};

/**
 * Signals in message AD_Control_Body.
 *
 * ADÄ£Ê½ÏÂbodyÇëÇó
ÓÉAD½Úµã·¢ËÍ£¬ÓÉVCU½Úµã½ÓÊÕ
 *
 * All signal values are as on the CAN bus.
 */
struct veh_dbc_ad_control_body_t {
    /**
     * 0±íÊ¾ÎÞÐ§£¬1±íÊ¾³µÉí²¿¼þ¿É¿Ø
     *
     * Range: 0..15 (0..15 N/A)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_body_valid;

    /**
     * ADÄ£Ê½ÏÂ£¬ÖÆ¶¯µÆÖ»ÓÉ¸ÃÐÅºÅ¿ØÖÆ£¬³ýÁË°´ÏÂ¼±Í££¨ºÍÒ£¿ØÆ÷¸øÖÆ¶¯£©£¬ÎÞÈÎºÎÆäËû¹ØÁª
     * 0ÖÆ¶¯µÆ¹Ø
     * 1ÖÆ¶¯µÆ¿ª
     *
     * Range: 0..1 (0..1 N/A)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_brake_light;

    /**
     * Ë«ÉÁ¿ØÖÆ
     * 0¹Ø
     * 1¿ª
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_double_flash_light;

    /**
     * µ¹³µµÆ¿ØÖÆ£¨ADÄ£Ê½ÏÂÎÞÈÎºÎ¹ØÁª£¬Ö»ÓÉ¸Ã½Ó¿Ú¿ØÖÆ£©
     * 0¹Ø
     * 1¿ª
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_reversing_lights;

    /**
     * 0±íÊ¾Ð¡µÆ¹Ø±Õ
     * 1±íÊ¾Ð¡µÆ¿ªÆô
     *
     * Range: 0..1 (0..1 N/A)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_low_beam;

    /**
     * 0±íÊ¾×ó×ªµÆ¹Ø±Õ
     * 1±íÊ¾×ó×ªµÆ¿ªÆô
     *
     * Range: 0..1 (0..1 N/A)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_left_turn_light;

    /**
     * 0±íÊ¾ÓÒ×ªµÆ¹Ø±Õ
     * 1±íÊ¾ÓÒ×ªµÆ¿ªÆô
     *
     * Range: 0..1 (0..1 N/A)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_right_turn_light;

    /**
     * 0µÍËÙ·äÃùÆ÷¹Ø
     * 1µÍËÙ·äÃùÆ÷¿ª
     *
     * Range: 0..1 (0..1 N/A)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_horn_control;

    /**
     * 0±íÊ¾´óµÆ¹Ø±Õ
     * 1±íÊ¾´óµÆ¿ªÆô
     *
     * Range: 0..1 (0..1 N/A)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_high_beam;

    /**
     * ÎíµÆ
     * 0±íÊ¾Î´¿ªÆô
     * 1±íÊ¾¿ªÆô
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_fof_light;

    /**
     * 0À®°È¹Ø
     * 1À®°È¿ª
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_horn_control_1;
};

/**
 * Signals in message AD_Control_Accelerate.
 *
 * ADÇý¶¯ÇëÇó
ÓÉAD½Úµã·¢ËÍ£¬ÓÉVCU½Úµã½ÓÊÕ
 *
 * All signal values are as on the CAN bus.
 */
struct veh_dbc_ad_control_accelerate_t {
    /**
     * 0±íÊ¾ÎÞÐ§£¬1±íÊ¾½øÈë×Ô¶¯¼ÝÊ»
     *
     * Range: 0..15 (0..15 N/A)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_accelerate_valid;

    /**
     * ×Ô¶¯¼ÝÊ»ÏÂ·¢µÄÄÜÁ¿»ØÊÕ±êÖ¾Î»
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_energy_recovery;

    /**
     * 0±íÊ¾Çý¶¯ÓÉÌ¤°å¿ØÖÆ£¬1±íÊ¾Çý¶¯ÓÉËÙ¶È¿ØÖÆ£¬2±íÊ¾Å¤¾Ø¿ØÖÆ
     *
     * Range: 0..2 (0..2 N/A)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_accelerate_work_mode;

    /**
     * 0:P×¤³µµµ  1£ºDÇ°½øµµ  2£ºN¿Õµµ  3£ºRºóÍËµµ
     *
     * Range: 0..3 (0..3 N/A)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_accelerate_gear;

    /**
     * Çý¶¯ÓÍÃÅ¿ª¶È0~100%£¬¶ÔÓ¦Å¤¾Ø0~90N.m
     *
     * Range: 0..100 (0..100 %)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_torque_control;

    /**
     * ³µÁ¾ÇëÇó³µËÙ£¨km/h£©/ÇëÇóÅ¤¾Ø£¨N.m£©
     *
     * Range: 0..3000 (0..300 km/h)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t ad_speedor_torque_control;
};

/**
 * Signals in message AD_Control_Brake.
 *
 * ADÖÆ¶¯ÇëÇó
ÓÉAD½Úµã·¢ËÍ£¬ÓÉVCU½Úµã½ÓÊÕ
 *
 * All signal values are as on the CAN bus.
 */
struct veh_dbc_ad_control_brake_t {
    /**
     * 0±íÊ¾ÎÞÐ§£¬1±íÊ¾ÖÆ¶¯¿É¿Ø
     *
     * Range: 0..15 (0..15 N/A)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_dbs_valid;

    /**
     * EPBµ¥±ß´ò»¬±êÖ¾Î»
     * 0£ºÎ´¿ªÆô
     * 1£º¿ªÆô
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_awsc_flag;

    /**
     * AD¿ØÖÆÅÅÆøÄ£Ê½½Ó¿Ú
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_dbs_workmode;

    /**
     * ÖÆ¶¯Ì¤°å£¨0~100%£©£¬¶ÔÓ¦0-10MpaÑ¹Á¦ÇëÇó
     * 
     *
     * Range: 0..100 (0..100 %)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_brake_pressure_cmd;
};

/**
 * Signals in message AD_Control_Steering.
 *
 * AD×ªÏòÇëÇó
ÓÉAD½Úµã·¢ËÍ£¬ÓÉVCU½Úµã½ÓÊÕ
 *
 * All signal values are as on the CAN bus.
 */
struct veh_dbc_ad_control_steering_t {
    /**
     * 0±íÊ¾ÎÞÐ§£¬1±íÊ¾×ªÏò¿É¿Ø
     *
     * Range: 0..15 (0..15 N/A)
     * Scale: 1
     * Offset: 0
     */
    uint8_t ad_steering_valid;

    /**
     * ÂÖ¶Ë×ªÏò½ÇËÙ¶È¿ØÖÆ
     *
     * Range: 0..252 (2.68..27.86 -)
     * Scale: 0.1
     * Offset: 2.68
     */
    uint8_t ad_steering_speed_cmd;

    /**
     * ADÄ£Ê½ÏÂ£¬-30µ½+30¶È ×ª½ÇÇëÇó£¨×óÕýÓÒ¸º£©
     *
     * Range: 0..600 (-30..30 deg)
     * Scale: 0.1
     * Offset: -30
     */
    uint16_t ad_steering_angle_cmd;
};

/**
 * Pack message AD_Control_Device.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int veh_dbc_ad_control_device_pack(
    uint8_t *dst_p,
    const struct veh_dbc_ad_control_device_t *src_p,
    size_t size);

/**
 * Unpack message AD_Control_Device.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int veh_dbc_ad_control_device_unpack(
    struct veh_dbc_ad_control_device_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from AD_Control_Device.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int veh_dbc_ad_control_device_init(struct veh_dbc_ad_control_device_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_control_device_ad_clean_fan_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_control_device_ad_clean_fan_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_control_device_ad_clean_fan_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_control_device_ad_move_mode_req_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_control_device_ad_move_mode_req_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_control_device_ad_move_mode_req_is_in_range(uint8_t value);

/**
 * Pack message AD_Setup_Control.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int veh_dbc_ad_setup_control_pack(
    uint8_t *dst_p,
    const struct veh_dbc_ad_setup_control_t *src_p,
    size_t size);

/**
 * Unpack message AD_Setup_Control.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int veh_dbc_ad_setup_control_unpack(
    struct veh_dbc_ad_setup_control_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from AD_Setup_Control.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int veh_dbc_ad_setup_control_init(struct veh_dbc_ad_setup_control_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_setup_control_ad_release_emergency_button_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_setup_control_ad_release_emergency_button_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_setup_control_ad_release_emergency_button_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_setup_control_ad_release_f_bumper_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_setup_control_ad_release_f_bumper_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_setup_control_ad_release_f_bumper_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_setup_control_ad_release_b_bumper_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_setup_control_ad_release_b_bumper_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_setup_control_ad_release_b_bumper_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_setup_control_ad_release_l_bumper_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_setup_control_ad_release_l_bumper_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_setup_control_ad_release_l_bumper_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_setup_control_ad_release_r_bumper_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_setup_control_ad_release_r_bumper_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_setup_control_ad_release_r_bumper_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_setup_control_ad_clear_trip_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_setup_control_ad_clear_trip_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_setup_control_ad_clear_trip_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_setup_control_ad_disable_f_bumper_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_setup_control_ad_disable_f_bumper_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_setup_control_ad_disable_f_bumper_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_setup_control_ad_disable_b_bumper_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_setup_control_ad_disable_b_bumper_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_setup_control_ad_disable_b_bumper_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_setup_control_ad_disable_l_bumper_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_setup_control_ad_disable_l_bumper_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_setup_control_ad_disable_l_bumper_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_setup_control_ad_disable_r_bumper_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_setup_control_ad_disable_r_bumper_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_setup_control_ad_disable_r_bumper_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_setup_control_can_sign_tran_state_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_setup_control_can_sign_tran_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_setup_control_can_sign_tran_state_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t veh_dbc_ad_setup_control_ad_vehicle_weight_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_setup_control_ad_vehicle_weight_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_setup_control_ad_vehicle_weight_is_in_range(uint16_t value);

/**
 * Pack message System_Power_Control.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int veh_dbc_system_power_control_pack(
    uint8_t *dst_p,
    const struct veh_dbc_system_power_control_t *src_p,
    size_t size);

/**
 * Unpack message System_Power_Control.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int veh_dbc_system_power_control_unpack(
    struct veh_dbc_system_power_control_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from System_Power_Control.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int veh_dbc_system_power_control_init(struct veh_dbc_system_power_control_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_system_power_control_ad_sys_power_control_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_system_power_control_ad_sys_power_control_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_system_power_control_ad_sys_power_control_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_system_power_control_reserved_sys_power_control_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_system_power_control_reserved_sys_power_control_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_system_power_control_reserved_sys_power_control_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_system_power_control_network_sys_power_control_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_system_power_control_network_sys_power_control_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_system_power_control_network_sys_power_control_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_system_power_control_radar_sys_power_control_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_system_power_control_radar_sys_power_control_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_system_power_control_radar_sys_power_control_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_system_power_control_business_sys_power_control_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_system_power_control_business_sys_power_control_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_system_power_control_business_sys_power_control_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_system_power_control_vehicle_work_mode_control_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_system_power_control_vehicle_work_mode_control_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_system_power_control_vehicle_work_mode_control_is_in_range(uint8_t value);

/**
 * Pack message Power_on_CAN.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int veh_dbc_power_on_can_pack(
    uint8_t *dst_p,
    const struct veh_dbc_power_on_can_t *src_p,
    size_t size);

/**
 * Unpack message Power_on_CAN.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int veh_dbc_power_on_can_unpack(
    struct veh_dbc_power_on_can_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Power_on_CAN.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int veh_dbc_power_on_can_init(struct veh_dbc_power_on_can_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_power_on_can_vehicle_power_req_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_power_on_can_vehicle_power_req_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_power_on_can_vehicle_power_req_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_power_on_can_ad_power_off_delay_time_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_power_on_can_ad_power_off_delay_time_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_power_on_can_ad_power_off_delay_time_is_in_range(uint8_t value);

/**
 * Pack message AD_Control_Body.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int veh_dbc_ad_control_body_pack(
    uint8_t *dst_p,
    const struct veh_dbc_ad_control_body_t *src_p,
    size_t size);

/**
 * Unpack message AD_Control_Body.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int veh_dbc_ad_control_body_unpack(
    struct veh_dbc_ad_control_body_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from AD_Control_Body.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int veh_dbc_ad_control_body_init(struct veh_dbc_ad_control_body_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_control_body_ad_body_valid_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_control_body_ad_body_valid_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_control_body_ad_body_valid_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_control_body_ad_brake_light_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_control_body_ad_brake_light_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_control_body_ad_brake_light_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_control_body_ad_double_flash_light_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_control_body_ad_double_flash_light_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_control_body_ad_double_flash_light_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_control_body_ad_reversing_lights_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_control_body_ad_reversing_lights_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_control_body_ad_reversing_lights_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_control_body_ad_low_beam_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_control_body_ad_low_beam_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_control_body_ad_low_beam_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_control_body_ad_left_turn_light_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_control_body_ad_left_turn_light_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_control_body_ad_left_turn_light_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_control_body_ad_right_turn_light_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_control_body_ad_right_turn_light_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_control_body_ad_right_turn_light_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_control_body_ad_horn_control_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_control_body_ad_horn_control_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_control_body_ad_horn_control_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_control_body_ad_high_beam_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_control_body_ad_high_beam_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_control_body_ad_high_beam_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_control_body_ad_fof_light_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_control_body_ad_fof_light_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_control_body_ad_fof_light_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_control_body_ad_horn_control_1_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_control_body_ad_horn_control_1_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_control_body_ad_horn_control_1_is_in_range(uint8_t value);

/**
 * Pack message AD_Control_Accelerate.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int veh_dbc_ad_control_accelerate_pack(
    uint8_t *dst_p,
    const struct veh_dbc_ad_control_accelerate_t *src_p,
    size_t size);

/**
 * Unpack message AD_Control_Accelerate.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int veh_dbc_ad_control_accelerate_unpack(
    struct veh_dbc_ad_control_accelerate_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from AD_Control_Accelerate.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int veh_dbc_ad_control_accelerate_init(struct veh_dbc_ad_control_accelerate_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_control_accelerate_ad_accelerate_valid_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_control_accelerate_ad_accelerate_valid_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_control_accelerate_ad_accelerate_valid_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_control_accelerate_ad_energy_recovery_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_control_accelerate_ad_energy_recovery_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_control_accelerate_ad_energy_recovery_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_control_accelerate_ad_accelerate_work_mode_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_control_accelerate_ad_accelerate_work_mode_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_control_accelerate_ad_accelerate_work_mode_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_control_accelerate_ad_accelerate_gear_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_control_accelerate_ad_accelerate_gear_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_control_accelerate_ad_accelerate_gear_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_control_accelerate_ad_torque_control_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_control_accelerate_ad_torque_control_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_control_accelerate_ad_torque_control_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t veh_dbc_ad_control_accelerate_ad_speedor_torque_control_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_control_accelerate_ad_speedor_torque_control_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_control_accelerate_ad_speedor_torque_control_is_in_range(uint16_t value);

/**
 * Pack message AD_Control_Brake.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int veh_dbc_ad_control_brake_pack(
    uint8_t *dst_p,
    const struct veh_dbc_ad_control_brake_t *src_p,
    size_t size);

/**
 * Unpack message AD_Control_Brake.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int veh_dbc_ad_control_brake_unpack(
    struct veh_dbc_ad_control_brake_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from AD_Control_Brake.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int veh_dbc_ad_control_brake_init(struct veh_dbc_ad_control_brake_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_control_brake_ad_dbs_valid_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_control_brake_ad_dbs_valid_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_control_brake_ad_dbs_valid_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_control_brake_ad_awsc_flag_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_control_brake_ad_awsc_flag_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_control_brake_ad_awsc_flag_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_control_brake_ad_dbs_workmode_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_control_brake_ad_dbs_workmode_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_control_brake_ad_dbs_workmode_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_control_brake_ad_brake_pressure_cmd_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_control_brake_ad_brake_pressure_cmd_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_control_brake_ad_brake_pressure_cmd_is_in_range(uint8_t value);

/**
 * Pack message AD_Control_Steering.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int veh_dbc_ad_control_steering_pack(
    uint8_t *dst_p,
    const struct veh_dbc_ad_control_steering_t *src_p,
    size_t size);

/**
 * Unpack message AD_Control_Steering.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int veh_dbc_ad_control_steering_unpack(
    struct veh_dbc_ad_control_steering_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from AD_Control_Steering.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int veh_dbc_ad_control_steering_init(struct veh_dbc_ad_control_steering_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_control_steering_ad_steering_valid_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_control_steering_ad_steering_valid_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_control_steering_ad_steering_valid_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t veh_dbc_ad_control_steering_ad_steering_speed_cmd_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_control_steering_ad_steering_speed_cmd_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_control_steering_ad_steering_speed_cmd_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t veh_dbc_ad_control_steering_ad_steering_angle_cmd_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double veh_dbc_ad_control_steering_ad_steering_angle_cmd_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool veh_dbc_ad_control_steering_ad_steering_angle_cmd_is_in_range(uint16_t value);


#ifdef __cplusplus
}
#endif

#endif
