// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: can_gateway.proto

#include "can_gateway.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_can_5fgateway_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_can_5fgateway_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_CANMsgData;
}  // namespace protobuf_can_5fgateway_2eproto
namespace can_gateway {
class CANMsgDataDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CANMsgData>
      _instance;
} _CANMsgData_default_instance_;
class CANMsgDataListDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CANMsgDataList>
      _instance;
} _CANMsgDataList_default_instance_;
}  // namespace can_gateway
namespace protobuf_can_5fgateway_2eproto {
static void InitDefaultsCANMsgData() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::can_gateway::_CANMsgData_default_instance_;
    new (ptr) ::can_gateway::CANMsgData();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::can_gateway::CANMsgData::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_CANMsgData =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsCANMsgData}, {}};

static void InitDefaultsCANMsgDataList() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::can_gateway::_CANMsgDataList_default_instance_;
    new (ptr) ::can_gateway::CANMsgDataList();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::can_gateway::CANMsgDataList::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_CANMsgDataList =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsCANMsgDataList}, {
      &protobuf_can_5fgateway_2eproto::scc_info_CANMsgData.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_CANMsgData.base);
  ::google::protobuf::internal::InitSCC(&scc_info_CANMsgDataList.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::can_gateway::CANMsgData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::can_gateway::CANMsgData, canchannel_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::can_gateway::CANMsgData, canid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::can_gateway::CANMsgData, f_rtr_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::can_gateway::CANMsgData, f_canfd_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::can_gateway::CANMsgData, f_ide_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::can_gateway::CANMsgData, candatalen_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::can_gateway::CANMsgData, bytes_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::can_gateway::CANMsgData, seconds_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::can_gateway::CANMsgData, nanoseconds_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::can_gateway::CANMsgDataList, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::can_gateway::CANMsgDataList, messages_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::can_gateway::CANMsgData)},
  { 14, -1, sizeof(::can_gateway::CANMsgDataList)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::can_gateway::_CANMsgData_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::can_gateway::_CANMsgDataList_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "can_gateway.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\021can_gateway.proto\022\013can_gateway\"\247\001\n\nCAN"
      "MsgData\022\022\n\nCANChannel\030\001 \001(\r\022\r\n\005CanId\030\002 \001"
      "(\r\022\r\n\005f_RTR\030\003 \001(\010\022\017\n\007f_CANFD\030\004 \001(\010\022\r\n\005f_"
      "IDE\030\005 \001(\010\022\022\n\nCanDataLen\030\006 \001(\r\022\r\n\005Bytes\030\007"
      " \001(\014\022\017\n\007seconds\030\010 \001(\r\022\023\n\013nanoseconds\030\t \001"
      "(\r\";\n\016CANMsgDataList\022)\n\010messages\030\001 \003(\0132\027"
      ".can_gateway.CANMsgDatab\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 271);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "can_gateway.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_can_5fgateway_2eproto
namespace can_gateway {

// ===================================================================

void CANMsgData::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CANMsgData::kCANChannelFieldNumber;
const int CANMsgData::kCanIdFieldNumber;
const int CANMsgData::kFRTRFieldNumber;
const int CANMsgData::kFCANFDFieldNumber;
const int CANMsgData::kFIDEFieldNumber;
const int CANMsgData::kCanDataLenFieldNumber;
const int CANMsgData::kBytesFieldNumber;
const int CANMsgData::kSecondsFieldNumber;
const int CANMsgData::kNanosecondsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CANMsgData::CANMsgData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_can_5fgateway_2eproto::scc_info_CANMsgData.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:can_gateway.CANMsgData)
}
CANMsgData::CANMsgData(const CANMsgData& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  bytes_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.bytes().size() > 0) {
    bytes_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bytes_);
  }
  ::memcpy(&canchannel_, &from.canchannel_,
    static_cast<size_t>(reinterpret_cast<char*>(&nanoseconds_) -
    reinterpret_cast<char*>(&canchannel_)) + sizeof(nanoseconds_));
  // @@protoc_insertion_point(copy_constructor:can_gateway.CANMsgData)
}

void CANMsgData::SharedCtor() {
  bytes_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&canchannel_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&nanoseconds_) -
      reinterpret_cast<char*>(&canchannel_)) + sizeof(nanoseconds_));
}

CANMsgData::~CANMsgData() {
  // @@protoc_insertion_point(destructor:can_gateway.CANMsgData)
  SharedDtor();
}

void CANMsgData::SharedDtor() {
  bytes_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void CANMsgData::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* CANMsgData::descriptor() {
  ::protobuf_can_5fgateway_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_can_5fgateway_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CANMsgData& CANMsgData::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_can_5fgateway_2eproto::scc_info_CANMsgData.base);
  return *internal_default_instance();
}


void CANMsgData::Clear() {
// @@protoc_insertion_point(message_clear_start:can_gateway.CANMsgData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  bytes_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&canchannel_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&nanoseconds_) -
      reinterpret_cast<char*>(&canchannel_)) + sizeof(nanoseconds_));
  _internal_metadata_.Clear();
}

bool CANMsgData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:can_gateway.CANMsgData)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 CANChannel = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &canchannel_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 CanId = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &canid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool f_RTR = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &f_rtr_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool f_CANFD = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &f_canfd_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool f_IDE = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &f_ide_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 CanDataLen = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &candatalen_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes Bytes = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_bytes()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 seconds = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u /* 64 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &seconds_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 nanoseconds = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(72u /* 72 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &nanoseconds_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:can_gateway.CANMsgData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:can_gateway.CANMsgData)
  return false;
#undef DO_
}

void CANMsgData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:can_gateway.CANMsgData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 CANChannel = 1;
  if (this->canchannel() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->canchannel(), output);
  }

  // uint32 CanId = 2;
  if (this->canid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->canid(), output);
  }

  // bool f_RTR = 3;
  if (this->f_rtr() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->f_rtr(), output);
  }

  // bool f_CANFD = 4;
  if (this->f_canfd() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->f_canfd(), output);
  }

  // bool f_IDE = 5;
  if (this->f_ide() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(5, this->f_ide(), output);
  }

  // uint32 CanDataLen = 6;
  if (this->candatalen() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(6, this->candatalen(), output);
  }

  // bytes Bytes = 7;
  if (this->bytes().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      7, this->bytes(), output);
  }

  // uint32 seconds = 8;
  if (this->seconds() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(8, this->seconds(), output);
  }

  // uint32 nanoseconds = 9;
  if (this->nanoseconds() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(9, this->nanoseconds(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:can_gateway.CANMsgData)
}

::google::protobuf::uint8* CANMsgData::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:can_gateway.CANMsgData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 CANChannel = 1;
  if (this->canchannel() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->canchannel(), target);
  }

  // uint32 CanId = 2;
  if (this->canid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->canid(), target);
  }

  // bool f_RTR = 3;
  if (this->f_rtr() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->f_rtr(), target);
  }

  // bool f_CANFD = 4;
  if (this->f_canfd() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->f_canfd(), target);
  }

  // bool f_IDE = 5;
  if (this->f_ide() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(5, this->f_ide(), target);
  }

  // uint32 CanDataLen = 6;
  if (this->candatalen() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(6, this->candatalen(), target);
  }

  // bytes Bytes = 7;
  if (this->bytes().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        7, this->bytes(), target);
  }

  // uint32 seconds = 8;
  if (this->seconds() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(8, this->seconds(), target);
  }

  // uint32 nanoseconds = 9;
  if (this->nanoseconds() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(9, this->nanoseconds(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:can_gateway.CANMsgData)
  return target;
}

size_t CANMsgData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:can_gateway.CANMsgData)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes Bytes = 7;
  if (this->bytes().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->bytes());
  }

  // uint32 CANChannel = 1;
  if (this->canchannel() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->canchannel());
  }

  // uint32 CanId = 2;
  if (this->canid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->canid());
  }

  // bool f_RTR = 3;
  if (this->f_rtr() != 0) {
    total_size += 1 + 1;
  }

  // bool f_CANFD = 4;
  if (this->f_canfd() != 0) {
    total_size += 1 + 1;
  }

  // bool f_IDE = 5;
  if (this->f_ide() != 0) {
    total_size += 1 + 1;
  }

  // uint32 CanDataLen = 6;
  if (this->candatalen() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->candatalen());
  }

  // uint32 seconds = 8;
  if (this->seconds() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->seconds());
  }

  // uint32 nanoseconds = 9;
  if (this->nanoseconds() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->nanoseconds());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CANMsgData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:can_gateway.CANMsgData)
  GOOGLE_DCHECK_NE(&from, this);
  const CANMsgData* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CANMsgData>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:can_gateway.CANMsgData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:can_gateway.CANMsgData)
    MergeFrom(*source);
  }
}

void CANMsgData::MergeFrom(const CANMsgData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:can_gateway.CANMsgData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.bytes().size() > 0) {

    bytes_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bytes_);
  }
  if (from.canchannel() != 0) {
    set_canchannel(from.canchannel());
  }
  if (from.canid() != 0) {
    set_canid(from.canid());
  }
  if (from.f_rtr() != 0) {
    set_f_rtr(from.f_rtr());
  }
  if (from.f_canfd() != 0) {
    set_f_canfd(from.f_canfd());
  }
  if (from.f_ide() != 0) {
    set_f_ide(from.f_ide());
  }
  if (from.candatalen() != 0) {
    set_candatalen(from.candatalen());
  }
  if (from.seconds() != 0) {
    set_seconds(from.seconds());
  }
  if (from.nanoseconds() != 0) {
    set_nanoseconds(from.nanoseconds());
  }
}

void CANMsgData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:can_gateway.CANMsgData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CANMsgData::CopyFrom(const CANMsgData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:can_gateway.CANMsgData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CANMsgData::IsInitialized() const {
  return true;
}

void CANMsgData::Swap(CANMsgData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CANMsgData::InternalSwap(CANMsgData* other) {
  using std::swap;
  bytes_.Swap(&other->bytes_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(canchannel_, other->canchannel_);
  swap(canid_, other->canid_);
  swap(f_rtr_, other->f_rtr_);
  swap(f_canfd_, other->f_canfd_);
  swap(f_ide_, other->f_ide_);
  swap(candatalen_, other->candatalen_);
  swap(seconds_, other->seconds_);
  swap(nanoseconds_, other->nanoseconds_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata CANMsgData::GetMetadata() const {
  protobuf_can_5fgateway_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_can_5fgateway_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void CANMsgDataList::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CANMsgDataList::kMessagesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CANMsgDataList::CANMsgDataList()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_can_5fgateway_2eproto::scc_info_CANMsgDataList.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:can_gateway.CANMsgDataList)
}
CANMsgDataList::CANMsgDataList(const CANMsgDataList& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      messages_(from.messages_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:can_gateway.CANMsgDataList)
}

void CANMsgDataList::SharedCtor() {
}

CANMsgDataList::~CANMsgDataList() {
  // @@protoc_insertion_point(destructor:can_gateway.CANMsgDataList)
  SharedDtor();
}

void CANMsgDataList::SharedDtor() {
}

void CANMsgDataList::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* CANMsgDataList::descriptor() {
  ::protobuf_can_5fgateway_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_can_5fgateway_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CANMsgDataList& CANMsgDataList::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_can_5fgateway_2eproto::scc_info_CANMsgDataList.base);
  return *internal_default_instance();
}


void CANMsgDataList::Clear() {
// @@protoc_insertion_point(message_clear_start:can_gateway.CANMsgDataList)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  messages_.Clear();
  _internal_metadata_.Clear();
}

bool CANMsgDataList::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:can_gateway.CANMsgDataList)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .can_gateway.CANMsgData messages = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_messages()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:can_gateway.CANMsgDataList)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:can_gateway.CANMsgDataList)
  return false;
#undef DO_
}

void CANMsgDataList::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:can_gateway.CANMsgDataList)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .can_gateway.CANMsgData messages = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->messages_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->messages(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:can_gateway.CANMsgDataList)
}

::google::protobuf::uint8* CANMsgDataList::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:can_gateway.CANMsgDataList)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .can_gateway.CANMsgData messages = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->messages_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->messages(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:can_gateway.CANMsgDataList)
  return target;
}

size_t CANMsgDataList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:can_gateway.CANMsgDataList)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .can_gateway.CANMsgData messages = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->messages_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->messages(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CANMsgDataList::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:can_gateway.CANMsgDataList)
  GOOGLE_DCHECK_NE(&from, this);
  const CANMsgDataList* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CANMsgDataList>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:can_gateway.CANMsgDataList)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:can_gateway.CANMsgDataList)
    MergeFrom(*source);
  }
}

void CANMsgDataList::MergeFrom(const CANMsgDataList& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:can_gateway.CANMsgDataList)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  messages_.MergeFrom(from.messages_);
}

void CANMsgDataList::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:can_gateway.CANMsgDataList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CANMsgDataList::CopyFrom(const CANMsgDataList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:can_gateway.CANMsgDataList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CANMsgDataList::IsInitialized() const {
  return true;
}

void CANMsgDataList::Swap(CANMsgDataList* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CANMsgDataList::InternalSwap(CANMsgDataList* other) {
  using std::swap;
  CastToBase(&messages_)->InternalSwap(CastToBase(&other->messages_));
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata CANMsgDataList::GetMetadata() const {
  protobuf_can_5fgateway_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_can_5fgateway_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace can_gateway
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::can_gateway::CANMsgData* Arena::CreateMaybeMessage< ::can_gateway::CANMsgData >(Arena* arena) {
  return Arena::CreateInternal< ::can_gateway::CANMsgData >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::can_gateway::CANMsgDataList* Arena::CreateMaybeMessage< ::can_gateway::CANMsgDataList >(Arena* arena) {
  return Arena::CreateInternal< ::can_gateway::CANMsgDataList >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
