/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.13 Fri Jan 16 10:59:19 2026.
 */

#include <string.h>

#include "veh_dbc.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int veh_dbc_ad_control_device_pack(
    uint8_t *dst_p,
    const struct veh_dbc_ad_control_device_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->ad_clean_fan, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->ad_move_mode_req, 1u, 0x06u);

    return (8);
}

int veh_dbc_ad_control_device_unpack(
    struct veh_dbc_ad_control_device_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->ad_clean_fan = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->ad_move_mode_req = unpack_right_shift_u8(src_p[0], 1u, 0x06u);

    return (0);
}

int veh_dbc_ad_control_device_init(struct veh_dbc_ad_control_device_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct veh_dbc_ad_control_device_t));

    return 0;
}

uint8_t veh_dbc_ad_control_device_ad_clean_fan_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_control_device_ad_clean_fan_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_control_device_ad_clean_fan_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t veh_dbc_ad_control_device_ad_move_mode_req_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_control_device_ad_move_mode_req_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_control_device_ad_move_mode_req_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

int veh_dbc_ad_setup_control_pack(
    uint8_t *dst_p,
    const struct veh_dbc_ad_setup_control_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->ad_release_emergency_button, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->ad_release_f_bumper, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->ad_release_b_bumper, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->ad_release_l_bumper, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->ad_release_r_bumper, 4u, 0x10u);
    dst_p[1] |= pack_left_shift_u8(src_p->ad_clear_trip, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->ad_disable_f_bumper, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->ad_disable_b_bumper, 2u, 0x04u);
    dst_p[1] |= pack_left_shift_u8(src_p->ad_disable_l_bumper, 3u, 0x08u);
    dst_p[1] |= pack_left_shift_u8(src_p->ad_disable_r_bumper, 4u, 0x10u);
    dst_p[2] |= pack_left_shift_u8(src_p->can_sign_tran_state, 0u, 0x01u);
    dst_p[6] |= pack_left_shift_u16(src_p->ad_vehicle_weight, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->ad_vehicle_weight, 8u, 0x1fu);

    return (8);
}

int veh_dbc_ad_setup_control_unpack(
    struct veh_dbc_ad_setup_control_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->ad_release_emergency_button = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->ad_release_f_bumper = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->ad_release_b_bumper = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->ad_release_l_bumper = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->ad_release_r_bumper = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->ad_clear_trip = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->ad_disable_f_bumper = unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->ad_disable_b_bumper = unpack_right_shift_u8(src_p[1], 2u, 0x04u);
    dst_p->ad_disable_l_bumper = unpack_right_shift_u8(src_p[1], 3u, 0x08u);
    dst_p->ad_disable_r_bumper = unpack_right_shift_u8(src_p[1], 4u, 0x10u);
    dst_p->can_sign_tran_state = unpack_right_shift_u8(src_p[2], 0u, 0x01u);
    dst_p->ad_vehicle_weight = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->ad_vehicle_weight |= unpack_left_shift_u16(src_p[7], 8u, 0x1fu);

    return (0);
}

int veh_dbc_ad_setup_control_init(struct veh_dbc_ad_setup_control_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct veh_dbc_ad_setup_control_t));

    return 0;
}

uint8_t veh_dbc_ad_setup_control_ad_release_emergency_button_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_setup_control_ad_release_emergency_button_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_setup_control_ad_release_emergency_button_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t veh_dbc_ad_setup_control_ad_release_f_bumper_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_setup_control_ad_release_f_bumper_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_setup_control_ad_release_f_bumper_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t veh_dbc_ad_setup_control_ad_release_b_bumper_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_setup_control_ad_release_b_bumper_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_setup_control_ad_release_b_bumper_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t veh_dbc_ad_setup_control_ad_release_l_bumper_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_setup_control_ad_release_l_bumper_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_setup_control_ad_release_l_bumper_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t veh_dbc_ad_setup_control_ad_release_r_bumper_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_setup_control_ad_release_r_bumper_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_setup_control_ad_release_r_bumper_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t veh_dbc_ad_setup_control_ad_clear_trip_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_setup_control_ad_clear_trip_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_setup_control_ad_clear_trip_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t veh_dbc_ad_setup_control_ad_disable_f_bumper_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_setup_control_ad_disable_f_bumper_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_setup_control_ad_disable_f_bumper_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t veh_dbc_ad_setup_control_ad_disable_b_bumper_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_setup_control_ad_disable_b_bumper_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_setup_control_ad_disable_b_bumper_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t veh_dbc_ad_setup_control_ad_disable_l_bumper_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_setup_control_ad_disable_l_bumper_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_setup_control_ad_disable_l_bumper_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t veh_dbc_ad_setup_control_ad_disable_r_bumper_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_setup_control_ad_disable_r_bumper_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_setup_control_ad_disable_r_bumper_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t veh_dbc_ad_setup_control_can_sign_tran_state_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_setup_control_can_sign_tran_state_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_setup_control_can_sign_tran_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t veh_dbc_ad_setup_control_ad_vehicle_weight_encode(double value)
{
    return (uint16_t)(value);
}

double veh_dbc_ad_setup_control_ad_vehicle_weight_decode(uint16_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_setup_control_ad_vehicle_weight_is_in_range(uint16_t value)
{
    return (value <= 8191u);
}

int veh_dbc_system_power_control_pack(
    uint8_t *dst_p,
    const struct veh_dbc_system_power_control_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->ad_sys_power_control, 0u, 0x03u);
    dst_p[0] |= pack_left_shift_u8(src_p->reserved_sys_power_control, 2u, 0x0cu);
    dst_p[0] |= pack_left_shift_u8(src_p->network_sys_power_control, 4u, 0x30u);
    dst_p[0] |= pack_left_shift_u8(src_p->radar_sys_power_control, 6u, 0xc0u);
    dst_p[1] |= pack_left_shift_u8(src_p->business_sys_power_control, 0u, 0x03u);
    dst_p[4] |= pack_left_shift_u8(src_p->vehicle_work_mode_control, 0u, 0x03u);

    return (8);
}

int veh_dbc_system_power_control_unpack(
    struct veh_dbc_system_power_control_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->ad_sys_power_control = unpack_right_shift_u8(src_p[0], 0u, 0x03u);
    dst_p->reserved_sys_power_control = unpack_right_shift_u8(src_p[0], 2u, 0x0cu);
    dst_p->network_sys_power_control = unpack_right_shift_u8(src_p[0], 4u, 0x30u);
    dst_p->radar_sys_power_control = unpack_right_shift_u8(src_p[0], 6u, 0xc0u);
    dst_p->business_sys_power_control = unpack_right_shift_u8(src_p[1], 0u, 0x03u);
    dst_p->vehicle_work_mode_control = unpack_right_shift_u8(src_p[4], 0u, 0x03u);

    return (0);
}

int veh_dbc_system_power_control_init(struct veh_dbc_system_power_control_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct veh_dbc_system_power_control_t));

    return 0;
}

uint8_t veh_dbc_system_power_control_ad_sys_power_control_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_system_power_control_ad_sys_power_control_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_system_power_control_ad_sys_power_control_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t veh_dbc_system_power_control_reserved_sys_power_control_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_system_power_control_reserved_sys_power_control_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_system_power_control_reserved_sys_power_control_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t veh_dbc_system_power_control_network_sys_power_control_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_system_power_control_network_sys_power_control_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_system_power_control_network_sys_power_control_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t veh_dbc_system_power_control_radar_sys_power_control_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_system_power_control_radar_sys_power_control_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_system_power_control_radar_sys_power_control_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t veh_dbc_system_power_control_business_sys_power_control_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_system_power_control_business_sys_power_control_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_system_power_control_business_sys_power_control_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t veh_dbc_system_power_control_vehicle_work_mode_control_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_system_power_control_vehicle_work_mode_control_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_system_power_control_vehicle_work_mode_control_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

int veh_dbc_power_on_can_pack(
    uint8_t *dst_p,
    const struct veh_dbc_power_on_can_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->vehicle_power_req, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->ad_power_off_delay_time, 0u, 0x3fu);

    return (8);
}

int veh_dbc_power_on_can_unpack(
    struct veh_dbc_power_on_can_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->vehicle_power_req = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->ad_power_off_delay_time = unpack_right_shift_u8(src_p[1], 0u, 0x3fu);

    return (0);
}

int veh_dbc_power_on_can_init(struct veh_dbc_power_on_can_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct veh_dbc_power_on_can_t));

    return 0;
}

uint8_t veh_dbc_power_on_can_vehicle_power_req_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_power_on_can_vehicle_power_req_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_power_on_can_vehicle_power_req_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t veh_dbc_power_on_can_ad_power_off_delay_time_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_power_on_can_ad_power_off_delay_time_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_power_on_can_ad_power_off_delay_time_is_in_range(uint8_t value)
{
    return (value <= 63u);
}

int veh_dbc_ad_control_body_pack(
    uint8_t *dst_p,
    const struct veh_dbc_ad_control_body_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->ad_body_valid, 0u, 0x0fu);
    dst_p[1] |= pack_left_shift_u8(src_p->ad_brake_light, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->ad_double_flash_light, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->ad_reversing_lights, 2u, 0x04u);
    dst_p[1] |= pack_left_shift_u8(src_p->ad_low_beam, 3u, 0x08u);
    dst_p[1] |= pack_left_shift_u8(src_p->ad_left_turn_light, 4u, 0x10u);
    dst_p[1] |= pack_left_shift_u8(src_p->ad_right_turn_light, 5u, 0x20u);
    dst_p[1] |= pack_left_shift_u8(src_p->ad_horn_control, 6u, 0x40u);
    dst_p[1] |= pack_left_shift_u8(src_p->ad_high_beam, 7u, 0x80u);
    dst_p[2] |= pack_left_shift_u8(src_p->ad_fof_light, 0u, 0x01u);
    dst_p[3] |= pack_left_shift_u8(src_p->ad_horn_control_1, 0u, 0x01u);

    return (8);
}

int veh_dbc_ad_control_body_unpack(
    struct veh_dbc_ad_control_body_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->ad_body_valid = unpack_right_shift_u8(src_p[0], 0u, 0x0fu);
    dst_p->ad_brake_light = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->ad_double_flash_light = unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->ad_reversing_lights = unpack_right_shift_u8(src_p[1], 2u, 0x04u);
    dst_p->ad_low_beam = unpack_right_shift_u8(src_p[1], 3u, 0x08u);
    dst_p->ad_left_turn_light = unpack_right_shift_u8(src_p[1], 4u, 0x10u);
    dst_p->ad_right_turn_light = unpack_right_shift_u8(src_p[1], 5u, 0x20u);
    dst_p->ad_horn_control = unpack_right_shift_u8(src_p[1], 6u, 0x40u);
    dst_p->ad_high_beam = unpack_right_shift_u8(src_p[1], 7u, 0x80u);
    dst_p->ad_fof_light = unpack_right_shift_u8(src_p[2], 0u, 0x01u);
    dst_p->ad_horn_control_1 = unpack_right_shift_u8(src_p[3], 0u, 0x01u);

    return (0);
}

int veh_dbc_ad_control_body_init(struct veh_dbc_ad_control_body_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct veh_dbc_ad_control_body_t));

    return 0;
}

uint8_t veh_dbc_ad_control_body_ad_body_valid_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_control_body_ad_body_valid_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_control_body_ad_body_valid_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t veh_dbc_ad_control_body_ad_brake_light_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_control_body_ad_brake_light_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_control_body_ad_brake_light_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t veh_dbc_ad_control_body_ad_double_flash_light_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_control_body_ad_double_flash_light_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_control_body_ad_double_flash_light_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t veh_dbc_ad_control_body_ad_reversing_lights_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_control_body_ad_reversing_lights_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_control_body_ad_reversing_lights_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t veh_dbc_ad_control_body_ad_low_beam_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_control_body_ad_low_beam_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_control_body_ad_low_beam_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t veh_dbc_ad_control_body_ad_left_turn_light_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_control_body_ad_left_turn_light_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_control_body_ad_left_turn_light_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t veh_dbc_ad_control_body_ad_right_turn_light_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_control_body_ad_right_turn_light_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_control_body_ad_right_turn_light_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t veh_dbc_ad_control_body_ad_horn_control_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_control_body_ad_horn_control_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_control_body_ad_horn_control_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t veh_dbc_ad_control_body_ad_high_beam_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_control_body_ad_high_beam_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_control_body_ad_high_beam_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t veh_dbc_ad_control_body_ad_fof_light_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_control_body_ad_fof_light_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_control_body_ad_fof_light_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t veh_dbc_ad_control_body_ad_horn_control_1_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_control_body_ad_horn_control_1_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_control_body_ad_horn_control_1_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int veh_dbc_ad_control_accelerate_pack(
    uint8_t *dst_p,
    const struct veh_dbc_ad_control_accelerate_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->ad_accelerate_valid, 0u, 0x0fu);
    dst_p[0] |= pack_left_shift_u8(src_p->ad_energy_recovery, 4u, 0x10u);
    dst_p[2] |= pack_left_shift_u8(src_p->ad_accelerate_work_mode, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->ad_accelerate_gear, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->ad_torque_control, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->ad_speedor_torque_control, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->ad_speedor_torque_control, 8u, 0xffu);

    return (8);
}

int veh_dbc_ad_control_accelerate_unpack(
    struct veh_dbc_ad_control_accelerate_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->ad_accelerate_valid = unpack_right_shift_u8(src_p[0], 0u, 0x0fu);
    dst_p->ad_energy_recovery = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->ad_accelerate_work_mode = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->ad_accelerate_gear = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->ad_torque_control = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->ad_speedor_torque_control = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->ad_speedor_torque_control |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int veh_dbc_ad_control_accelerate_init(struct veh_dbc_ad_control_accelerate_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct veh_dbc_ad_control_accelerate_t));

    return 0;
}

uint8_t veh_dbc_ad_control_accelerate_ad_accelerate_valid_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_control_accelerate_ad_accelerate_valid_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_control_accelerate_ad_accelerate_valid_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t veh_dbc_ad_control_accelerate_ad_energy_recovery_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_control_accelerate_ad_energy_recovery_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_control_accelerate_ad_energy_recovery_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t veh_dbc_ad_control_accelerate_ad_accelerate_work_mode_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_control_accelerate_ad_accelerate_work_mode_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_control_accelerate_ad_accelerate_work_mode_is_in_range(uint8_t value)
{
    return (value <= 2u);
}

uint8_t veh_dbc_ad_control_accelerate_ad_accelerate_gear_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_control_accelerate_ad_accelerate_gear_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_control_accelerate_ad_accelerate_gear_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t veh_dbc_ad_control_accelerate_ad_torque_control_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_control_accelerate_ad_torque_control_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_control_accelerate_ad_torque_control_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

uint16_t veh_dbc_ad_control_accelerate_ad_speedor_torque_control_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double veh_dbc_ad_control_accelerate_ad_speedor_torque_control_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool veh_dbc_ad_control_accelerate_ad_speedor_torque_control_is_in_range(uint16_t value)
{
    return (value <= 3000u);
}

int veh_dbc_ad_control_brake_pack(
    uint8_t *dst_p,
    const struct veh_dbc_ad_control_brake_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->ad_dbs_valid, 0u, 0x0fu);
    dst_p[0] |= pack_left_shift_u8(src_p->ad_awsc_flag, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->ad_dbs_workmode, 5u, 0x20u);
    dst_p[1] |= pack_left_shift_u8(src_p->ad_brake_pressure_cmd, 0u, 0xffu);

    return (8);
}

int veh_dbc_ad_control_brake_unpack(
    struct veh_dbc_ad_control_brake_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->ad_dbs_valid = unpack_right_shift_u8(src_p[0], 0u, 0x0fu);
    dst_p->ad_awsc_flag = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->ad_dbs_workmode = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->ad_brake_pressure_cmd = unpack_right_shift_u8(src_p[1], 0u, 0xffu);

    return (0);
}

int veh_dbc_ad_control_brake_init(struct veh_dbc_ad_control_brake_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct veh_dbc_ad_control_brake_t));

    return 0;
}

uint8_t veh_dbc_ad_control_brake_ad_dbs_valid_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_control_brake_ad_dbs_valid_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_control_brake_ad_dbs_valid_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t veh_dbc_ad_control_brake_ad_awsc_flag_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_control_brake_ad_awsc_flag_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_control_brake_ad_awsc_flag_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t veh_dbc_ad_control_brake_ad_dbs_workmode_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_control_brake_ad_dbs_workmode_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_control_brake_ad_dbs_workmode_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t veh_dbc_ad_control_brake_ad_brake_pressure_cmd_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_control_brake_ad_brake_pressure_cmd_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_control_brake_ad_brake_pressure_cmd_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

int veh_dbc_ad_control_steering_pack(
    uint8_t *dst_p,
    const struct veh_dbc_ad_control_steering_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->ad_steering_valid, 0u, 0x0fu);
    dst_p[1] |= pack_left_shift_u8(src_p->ad_steering_speed_cmd, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->ad_steering_angle_cmd, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->ad_steering_angle_cmd, 8u, 0xffu);

    return (8);
}

int veh_dbc_ad_control_steering_unpack(
    struct veh_dbc_ad_control_steering_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->ad_steering_valid = unpack_right_shift_u8(src_p[0], 0u, 0x0fu);
    dst_p->ad_steering_speed_cmd = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->ad_steering_angle_cmd = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->ad_steering_angle_cmd |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);

    return (0);
}

int veh_dbc_ad_control_steering_init(struct veh_dbc_ad_control_steering_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct veh_dbc_ad_control_steering_t));

    return 0;
}

uint8_t veh_dbc_ad_control_steering_ad_steering_valid_encode(double value)
{
    return (uint8_t)(value);
}

double veh_dbc_ad_control_steering_ad_steering_valid_decode(uint8_t value)
{
    return ((double)value);
}

bool veh_dbc_ad_control_steering_ad_steering_valid_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t veh_dbc_ad_control_steering_ad_steering_speed_cmd_encode(double value)
{
    return (uint8_t)((value - 2.68) / 0.1);
}

double veh_dbc_ad_control_steering_ad_steering_speed_cmd_decode(uint8_t value)
{
    return (((double)value * 0.1) + 2.68);
}

bool veh_dbc_ad_control_steering_ad_steering_speed_cmd_is_in_range(uint8_t value)
{
    return (value <= 252u);
}

uint16_t veh_dbc_ad_control_steering_ad_steering_angle_cmd_encode(double value)
{
    return (uint16_t)((value - -30.0) / 0.1);
}

double veh_dbc_ad_control_steering_ad_steering_angle_cmd_decode(uint16_t value)
{
    return (((double)value * 0.1) + -30.0);
}

bool veh_dbc_ad_control_steering_ad_steering_angle_cmd_is_in_range(uint16_t value)
{
    return (value <= 600u);
}
